version: "3.4"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p0
    ports:
      - 5454:5432
    environment:
      AUTH_TYPE: "trust"
      DB_NAME: "postgres"
      DB_HOST: "postgres"
      POOL_MODE: "transaction"
      MAX_PREPARED_STATEMENTS: ${MAX_PREPARED_STATEMENTS}
    depends_on:
      - postgres
